/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wattu_sidpi_GPIOController */

#ifndef _Included_com_wattu_sidpi_GPIOController
#define _Included_com_wattu_sidpi_GPIOController
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wattu_sidpi_GPIOController_MODE_IN
#define com_wattu_sidpi_GPIOController_MODE_IN 0L
#undef com_wattu_sidpi_GPIOController_MODE_OUT
#define com_wattu_sidpi_GPIOController_MODE_OUT 1L
#undef com_wattu_sidpi_GPIOController_MODE_CLOCK
#define com_wattu_sidpi_GPIOController_MODE_CLOCK 3L
#undef com_wattu_sidpi_GPIOController_VALUE_HIGH
#define com_wattu_sidpi_GPIOController_VALUE_HIGH 1L
#undef com_wattu_sidpi_GPIOController_VALUE_LOW
#define com_wattu_sidpi_GPIOController_VALUE_LOW 0L
/*
 * Class:     com_wattu_sidpi_GPIOController
 * Method:    wiringPiSetup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wattu_sidpi_GPIOController_wiringPiSetup
  (JNIEnv *, jclass);

/*
 * Class:     com_wattu_sidpi_GPIOController
 * Method:    pinMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wattu_sidpi_GPIOController_pinMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wattu_sidpi_GPIOController
 * Method:    digitalWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wattu_sidpi_GPIOController_digitalWrite
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wattu_sidpi_GPIOController
 * Method:    digitalRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wattu_sidpi_GPIOController_digitalRead
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wattu_sidpi_GPIOController
 * Method:    gpioClockSet
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wattu_sidpi_GPIOController_gpioClockSet
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wattu_sidpi_GPIOController
 * Method:    readByte
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wattu_sidpi_GPIOController_readByte
  (JNIEnv *, jobject);

/*
 * Class:     com_wattu_sidpi_GPIOController
 * Method:    writeByte
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wattu_sidpi_GPIOController_writeByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wattu_sidpi_GPIOController
 * Method:    setPins
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_com_wattu_sidpi_GPIOController_setPins
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     com_wattu_sidpi_GPIOController
 * Method:    startClock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wattu_sidpi_GPIOController_startClock
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
