/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wattu_sidpi_GPIOController */

#ifndef _Included_com_wattu_sidpi_GPIOController
#define _Included_com_wattu_sidpi_GPIOController
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wattu_sidpi_GPIOController_MODE_IN
#define com_wattu_sidpi_GPIOController_MODE_IN 0L
#undef com_wattu_sidpi_GPIOController_MODE_OUT
#define com_wattu_sidpi_GPIOController_MODE_OUT 1L
#undef com_wattu_sidpi_GPIOController_MODE_CLOCK
#define com_wattu_sidpi_GPIOController_MODE_CLOCK 3L
#undef com_wattu_sidpi_GPIOController_VALUE_HIGH
#define com_wattu_sidpi_GPIOController_VALUE_HIGH 1L
#undef com_wattu_sidpi_GPIOController_VALUE_LOW
#define com_wattu_sidpi_GPIOController_VALUE_LOW 0L
#ifdef __cplusplus
}
#endif
#endif
