/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wattu_sidpi_impl_GPIOControllerImpl */

#ifndef _Included_com_wattu_sidpi_impl_GPIOControllerImpl
#define _Included_com_wattu_sidpi_impl_GPIOControllerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wattu_sidpi_impl_GPIOControllerImpl
 * Method:    wiringPiSetup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_wattu_sidpi_impl_GPIOControllerImpl_wiringPiSetup
  (JNIEnv *, jclass);

/*
 * Class:     com_wattu_sidpi_impl_GPIOControllerImpl
 * Method:    clockSpeed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wattu_sidpi_impl_GPIOControllerImpl_clockSpeed
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wattu_sidpi_impl_GPIOControllerImpl
 * Method:    setPins
 * Signature: ([I[I)V
 */
JNIEXPORT void JNICALL Java_com_wattu_sidpi_impl_GPIOControllerImpl_setPins
  (JNIEnv *, jobject, jintArray, jintArray);

/*
 * Class:     com_wattu_sidpi_impl_GPIOControllerImpl
 * Method:    setPin
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wattu_sidpi_impl_GPIOControllerImpl_setPin
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_wattu_sidpi_impl_GPIOControllerImpl
 * Method:    getPin
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wattu_sidpi_impl_GPIOControllerImpl_getPin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_wattu_sidpi_impl_GPIOControllerImpl
 * Method:    getPins
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_wattu_sidpi_impl_GPIOControllerImpl_getPins
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_wattu_sidpi_impl_GPIOControllerImpl
 * Method:    setPinMode
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wattu_sidpi_impl_GPIOControllerImpl_setPinMode
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
